(if_statement) @if
(else_clause) @else
(for_statement) @for
(for_each_statement) @foreach
(while_statement) @while
(do_statement) @do
(switch_statement) @switch
(try_statement) @try
(catch_clause) @catch
(finally_clause) @finally
(using_statement) @using
(lock_statement) @lock
(with_statement) @with
(yield_statement) @yield
(return_statement) @return
(break_statement) @break
(continue_statement) @continue
(throw_statement) @throw
